### ISSUE TITLE
Tinker Combo Script

### ISSUE THREAD

**Issue by juzjus10** [snajdovski/Dota-2-Hacks-Open-Source-JS-API-#13]
I tried making a tinker combo script  

Soul Ring > Sheepstick > Ethereal > Dagon > Missile > Laser > Rearm  

this is my code 

```
var combo: Combo
module = {
	name: "Combo_Tinker",
	onPreload: (): void => {
        combo = new Combo()
        combo.addAbility("item_soul_ring", EComboAction.NO_TARGET)
        combo.addAbility("item_blink", EComboAction.CURSOR_ENEMY)
        combo.addAbility("item_sheepstick", EComboAction.CURSOR_ENEMY) 
        combo.addAbility("item_ethereal_blade", EComboAction.CURSOR_ENEMY)
	combo.addAbility(/item_dagon/, EComboAction.CURSOR_ENEMY)
        combo.addAbility("tinker_heat_seeking_missile", EComboAction.NO_TARGET)
        combo.addAbility("tinker_laser", EComboAction.CURSOR_ENEMY)
        combo.addAbility("tinker_rearm", EComboAction.NO_TARGET)
		if(!Corona.Commands.TinkerCombo) {
			Corona.Commands.TinkerCombo = () => combo.execute(EntityManager.MyEnt)
			Game.AddCommand("__ComboTinker", Corona.Commands.TinkerCombo, "", 0)
		}
	},
	isVisible: false
}

```
Im having issues where after trying the combo several times in demo mode, its starts to break. 

- Double Rearm
- Skips the Items 
- Does not use laser
- Rearm getting looped

I also get this warning from console 
`CDOTAPlayer::AddExecuteOrders: Player 0 () has potentially attempted to crash the server.`

**Comment by snajdovski** [comment]
Probably I will need to rewrite the Combo API its causing problems all the time, it is not all that reliable and stable.
I will look into it when I have more time.

**Comment by snajdovski** [comment]
> I tried making a tinker combo script
> 
> Soul Ring > Sheepstick > Ethereal > Dagon > Missile > Laser > Rearm
> 
> this is my code
> 
> ```
> var combo: Combo
> module = {
> 	name: "Combo_Tinker",
> 	onPreload: (): void => {
>         combo = new Combo()
>         combo.addAbility("item_soul_ring", EComboAction.NO_TARGET)
>         combo.addAbility("item_blink", EComboAction.CURSOR_ENEMY)
>         combo.addAbility("item_sheepstick", EComboAction.CURSOR_ENEMY) 
>         combo.addAbility("item_ethereal_blade", EComboAction.CURSOR_ENEMY)
> 	combo.addAbility(/item_dagon/, EComboAction.CURSOR_ENEMY)
>         combo.addAbility("tinker_heat_seeking_missile", EComboAction.NO_TARGET)
>         combo.addAbility("tinker_laser", EComboAction.CURSOR_ENEMY)
>         combo.addAbility("tinker_rearm", EComboAction.NO_TARGET)
> 		if(!Corona.Commands.TinkerCombo) {
> 			Corona.Commands.TinkerCombo = () => combo.execute(EntityManager.MyEnt)
> 			Game.AddCommand("__ComboTinker", Corona.Commands.TinkerCombo, "", 0)
> 		}
> 	},
> 	isVisible: false
> }
> ```
> 
> Im having issues where after trying the combo several times in demo mode, its starts to break.
> 
> * Double Rearm
> * Skips the Items
> * Does not use laser
> * Rearm getting looped
> 
> I also get this warning from console
> `CDOTAPlayer::AddExecuteOrders: Player 0 (1100889806) has potentially attempted to crash the server.`

After Playing around I think the issue is demo mode, the entities or better known enemies are not the same  as in the lobby so try into a loby when you develop hacks.

**Comment by juzjus10** [comment]
didnt realize my player id was there

**Comment by juzjus10** [comment]
Any idea on how to have a condition if the current ability is being channeled?  It seems like the double rearm happens when you execute the combo while Rearm is channeling

**Comment by snajdovski** [comment]
> didnt realize my player id was there 

No worries, you are right about the ulti of tinker , I will rewrite the script and post it tommorow/today stay tunned :)

**Comment by snajdovski** [comment]
> didnt realize my player id was there

Make sure to test the script in Lobby NOT in DEMO MODE

```
var combo: Combo

module = {
	name: "Combo_Tinker",
	onPreload: (): void => {
		combo = new Combo()
	
		combo.addAbility("tinker_rearm",EComboAction.NO_TARGET)
        combo.addAbility("item_soul_ring", EComboAction.NO_TARGET)
        combo.addAbility("item_blink", EComboAction.CURSOR_ENEMY)
        combo.addAbility("item_sheepstick", EComboAction.CURSOR_ENEMY) 
        combo.addAbility("item_ethereal_blade", EComboAction.CURSOR_ENEMY)
	    combo.addAbility(/item_dagon/, EComboAction.CURSOR_ENEMY)
        combo.addAbility("tinker_heat_seeking_missile", EComboAction.NO_TARGET)
		combo.addAbility("tinker_laser", EComboAction.CURSOR_ENEMY)
	
    
		if(!Corona.Commands.TinkerCombo) {
			Corona.Commands.TinkerCombo = () => combo.execute(EntityManager.MyEnt)
			Game.AddCommand("__ComboTinker", Corona.Commands.TinkerCombo, "", 0)
		}
	},
	isVisible: false
}

```

It could be better but the combo API needs rework, its good enough I have tested it, make sure with your mouse to aim at enemy spawned in Lobby. (Go to Play Dota and Create a lobby dont use DEMO for developing hacks)
JS API is limited in demo mode so use lobby again. xD (Making sure you read that you dont use demo for testing)
