### ISSUE TITLE
linux support?

### ISSUE THREAD

**Issue by miguelshta21** [snajdovski/Dota-2-Hacks-Open-Source-JS-API-#17]
hello it works in linux OS?

**Comment by ViniciusFXavier** [comment]
> hello it works in linux OS?

It is working, but you have to create the '.vpk' file.
If you have knowledge of 'C ++' I recommend this project also.
- MvDota: https://github.com/LWSS/McDota/

**Comment by miguelshta21** [comment]
(It only works on Linux.) McDota: https://github.com/LWSS/McDota/
i have tried it and when it say " injected sucefully" i've tried to open menu and nothing happens

**Comment by miguelshta21** [comment]
cant run build.bat on my linux
```	{
			// These are optional language paths. They must be mounted first, which is why there are first in the list.
			// *LANGUAGE* will be replaced with the actual language name. If not running a specific language, these paths will not be mounted
			Game_Language		dota_*LANGUAGE*

			// These are optional low-violence paths. They will only get mounted if you're in a low-violence mode.
			Game_LowViolence	dota_lv
					
			Game				corona
			
				
			Game				dota
			Game				core

			Mod					dota

			AddonRoot			dota_addons

			// Note: addon content is included in publiccontent by default.
			PublicContent		dota_core
			PublicContent		core
		}```

**Comment by miguelshta21** [comment]
it works now but how can i open the terminal only gui has opened

**Comment by ViniciusFXavier** [comment]
@miguelshta21 You have to add the `-dev` argument so that you can open the terminal within the game.

**Comment by ViniciusFXavier** [comment]
> (It only works on Linux.) McDota: https://github.com/LWSS/McDota/
> i have tried it and when it say " injected sucefully" i've tried to open menu and nothing happens

Wow.

Sometimes it works with me and sometimes it doesn't

**Comment by ViniciusFXavier** [comment]
> cant run build.bat on my linux
> 
> ```
> 			// These are optional language paths. They must be mounted first, which is why there are first in the list.
> 			// *LANGUAGE* will be replaced with the actual language name. If not running a specific language, these paths will not be mounted
> 			Game_Language		dota_*LANGUAGE*
> 
> 			// These are optional low-violence paths. They will only get mounted if you're in a low-violence mode.
> 			Game_LowViolence	dota_lv
> 					
> 			Game				corona
> 			
> 				
> 			Game				dota
> 			Game				core
> 
> 			Mod					dota
> 
> 			AddonRoot			dota_addons
> 
> 			// Note: addon content is included in publiccontent by default.
> 			PublicContent		dota_core
> 			PublicContent		core
> 		}```
> ```

If you already have NodeJS installed correctly, you don't need to run `build.bat` just run the `npm run build` command.
