### ISSUE TITLE
UI Settings does not save

### ISSUE THREAD

**Issue by juzjus10** [snajdovski/Dota-2-Hacks-Open-Source-JS-API-#3]
After a match, the UI resets and I need to enable the scripts again

**Comment by snajdovski** [comment]
Well, I am not sure how I can fix this as the .conf files are read when you are in Dota 2 Pick Phase if you enable many of the scripts won't work in pick phase, so I would need to think of a system on how to load the settings when you are in the actual game. I will try to fix this as it is anoying
