### ISSUE TITLE
Last hit

### ISSUE THREAD

**Issue by Sahib7777** [snajdovski/Dota-2-Hacks-Open-Source-JS-API-#4]
This is a great tool, i dont mean to be rude, but i am curious about the " __Maphack " terminal commands, what does that do , and also is there any last hit script loaded into corona , thanks again for this wonderfull tool ! keep updating 👯‍♂️

**Comment by snajdovski** [comment]
__Maphack will not work Valve patched this back in May 2018 , for last hit script I will build one soon.

**Comment by snajdovski** [comment]
@Sahib7777  Commited new script test for auto hit go and check it out.
