### ISSUE TITLE
Error - Error parsing layout and style files

### ISSUE THREAD

**Issue by ViniciusFXavier** [snajdovski/Dota-2-Hacks-Open-Source-JS-API-#8]
Every time I open the program I get this error.
This time I managed to take a print.

I have this error since 2020-06-01 before that I didn't have the error.

![image](https://user-images.githubusercontent.com/40774281/83700365-05b00a80-a5dd-11ea-912f-07a9bdf9aa33.png)

And when I click OK it will work normally again, this error started to happen after a 55MB dota 2 update

**Comment by snajdovski** [comment]
Go to hud.xml and delete 
		<Label id="ScriptsName" text="Corona v 0.2.0" style='width: 250px;**position: 310px**;'/>
I think position tag is not necessery
